# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Safran Bin Kader
title: Computer Science Major
email: binkades@myumanitoba.ca
website: sbinkader.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: sbinkader
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/originalProfile1.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Safran and I'm a fourth year computer science major student. Throughout my degree I have worked on a variety of projects and developed a passion for front-end dev using various industry standard frameworks. I am most skilled in: <mark>react</mark> and <mark>Mantine</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Database Project
        #link: github.com/ColinMcD6/DatabaseProject
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/ColinMcD6/DatabaseProject
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This was one of the first group project that I worked on and I learned a lot about working in a team and using databases.
        description: | # this will include new lines to allow paragraphs
          This project was part of my third year course work in COMP 3380, and was a group project with 2 other students. We were tasked with creating a database, and also had to create an interface to interact with the database. I was responsible for the adjustments and modifications of the terminal interface, and I also used my knowledge of <mark>SQL</mark> to create the database, populate it with data and make interesting <mark>queries</mark>.

      - layout: left
        title: Human Computer Interaction Project
        #link: github.com/ColinMcD6/DatabaseProject
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/NicBG/Grocery-Store-Interface
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The very first project that introduced me to the world of front-end development and react, and it was love at first sight.
        description: | # this will include new lines to allow paragraphs
          This was part of my third year course work in COMP 3020, and we were tasked with creating an interactive library that employed gestalt principles to reduce friction between human and computer.
          Being the lead front-end developer with the highest number of commit contributions, I was responsible for creating the interface using <mark>react</mark> and make it come to life. Some of the particular components that I created were the search bar, navigation arrows and feedback driven animations throughout the interface.

      - layout: left
        title: Software Engineering 1 Project
        #link: github.com/ColinMcD6/DatabaseProject
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sbinkader/G3Canada
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Software Engineering 1 was a great course that taught me a lot about working in a team and using agile methodologies.
        description: | # this will include new lines to allow paragraphs
          This was part of my third year course work in COMP 3350, and we were tasked with creating an Android application using <mark>Android Studio</mark>. The application that we picked was about food recipes, and part of my responsibilities included creating the front-end component of creating a recipe and viewing a recipe. I also worked on the back-end component of the application, which included creating a database, adding images and connecting it to the front-end.
          I was also part of testing and was responsible for creating test cases for unit, integration and acceptance tests and testing the application.

      - layout: left
        title: Software Engineering 2 Project (Current Project)
        #link: github.com/ColinMcD6/DatabaseProject
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/br-cz/neighbourhood
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Taking my software engineering skills to the next level, I am currently working on a project that is much more complex.
        description: | # this will include new lines to allow paragraphs
          This is part of my fourth year course work in COMP 4350, and my team is tasked with creating a web application. For this one, we have picked to create a brand-new social media platform that is based on the idea of having close knit communities.
          I am the second lead front-end developer and I am responsible for creating multiple components of the interface. I am using react as our core framework for front-end development, and for components I have worked extensively with the <mark>Mantine</mark> library.
          I have also worked with <mark>Formik</mark> for form handling, <mark>yup</mark> for schema validations, and I am also responsible for integrating the back-end component of the application using various AWS services like <mark>Amplify</mark>, <mark>Lambda</mark>, <mark>AppSync</mark>, <mark>DynamoDB</mark>, <mark>CloudWatch</mark>.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vital Statistics Manitoba
        link: vitalstats.gov.mb.ca/
        # link_text: boringcompany.com
        sub_title: Administrative Clerk
        caption: January 2022 - May 2023
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          *	Operated the computer databases of Vital Statistics to update client information on various fronts of the total database.
          *	Performed daily clerical duties including but not limited to processing event certificates, refilling stationary inventories, photocopying etc.
          *	Assisted the manager in routine access of confidential information vault to perform archival duties like maintenance and update of old archives.
          *	Worked with the manager to ensure that other daily branch operational requirements are being met.

      - layout: left
        title: Sobeys Bakery
        link: sobeys.com/stores/sobeys-pembina/
        # link_text: boringcompany.com
        sub_title: Front End Associate
        caption: August 2021 - January 2022
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          *	Handle range of client service situations to provide a tailored customer service experience.
          *	Work in conjunction with other departments to ensure a better shopping environment.
          *	Handle and package different types of baked and retail goods and put them on display.
          *	Work with the assistant manager & manager to ensure departmental operational requirements are daily met.

      - layout: left
        title: Manitoba Health
        link: gov.mb.ca/health/
        # link_text: boringcompany.com
        sub_title: Documentation  Clerk
        caption: November 2020 - April 2021
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          *	Filled information on documentations to maintain smooth operation of multiple branches of Manitoba Health.
          *	Operated computer databases of Manitoba Health to review and keep client information up to date.
          *	Sorted and managed client paper works in its own accordance.
          *	Handled a diverse range of insurance claims and processed such documents accordingly.
          *	Worked hand in hand with the manager and the supervisor to maintain daily responsibilities in a prioritized basis.

      - layout: left
        title: Starbucks
        link: starbucks.ca/
        # link_text: boringcompany.com
        sub_title: Barista
        caption: September 2019 - March 2020
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          *	Maintained customer satisfaction with strategic communication methods to address customer needs.
          *	With active listening, collaborated with customers to better provide solutions tailored specifically for them.
          *	Handled a diverse range of client service operations daily like operating the cash register.
          *	Handled deliveries with focus on the ease of co-workerâ€™s access to the inventory.
          *	Made lists and predicted needs of inventories to keep up with the demands.
          *	Worked closely with the supervisor and the manager to better understand the goals of the company and strategies to implement in diverse range of situations.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Manitoba
        caption: 2019 - Current
        sub_title: BSc Computer Science
        quote: >
          Established in 1877, University of Manitoba is one of the oldest higher education institution in Canada and has a strong research focus with a Nobel Prize winning faculty.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Gaming
      - Lifting Weights?
    # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

    # Look at this cool image
    # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
